{
	"id": "RLSA-2020:3185",
	"advisories": [
		{
			"content": {
				"id": "RLSA-2020:3185",
				"title": "Important: python-pillow security update",
				"description": "The python-pillow packages contain a Python image processing library that provides extensive file format support, an efficient internal representation, and powerful image-processing capabilities.\n\nSecurity Fix(es):\n\n* python-pillow: out-of-bounds reads/writes in the parsing of SGI image files in expandrow/expandrow2 (CVE-2020-11538)\n\n* python-pillow: out-of-bounds read in ImagingFliDecode when loading FLI images (CVE-2020-5313)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
				"severity": [
					{
						"type": "vendor",
						"source": "errata.rockylinux.org",
						"vendor": "IMPORTANT"
					}
				],
				"references": [
					{
						"source": "MITRE",
						"url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-11538"
					},
					{
						"source": "MITRE",
						"url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-5313"
					},
					{
						"source": "Red Hat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1789532"
					},
					{
						"source": "Red Hat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1852814"
					},
					{
						"source": "errata.rockylinux.org",
						"url": "https://errata.rockylinux.org/RLSA-2020:3185"
					}
				],
				"published": "2020-07-28T13:17:06Z"
			},
			"segments": [
				{
					"ecosystem": "rocky:8"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2020-11538",
				"severity": [
					{
						"type": "cvss_v31",
						"source": "MITRE",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
							"base_score": 8.1,
							"base_severity": "HIGH",
							"temporal_score": 8.1,
							"temporal_severity": "HIGH",
							"environmental_score": 8.1,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "MITRE",
						"cwe": [
							"CWE-122"
						]
					}
				],
				"references": [
					{
						"source": "MITRE",
						"url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-11538"
					}
				]
			},
			"segments": [
				{
					"ecosystem": "rocky:8"
				}
			]
		},
		{
			"content": {
				"id": "CVE-2020-5313",
				"severity": [
					{
						"type": "cvss_v31",
						"source": "MITRE",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:H",
							"base_score": 8.2,
							"base_severity": "HIGH",
							"temporal_score": 8.2,
							"temporal_severity": "HIGH",
							"environmental_score": 8.2,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "MITRE",
						"cwe": [
							"CWE-125"
						]
					}
				],
				"references": [
					{
						"source": "MITRE",
						"url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-5313"
					}
				]
			},
			"segments": [
				{
					"ecosystem": "rocky:8"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "rocky:8",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterions": [
							{
								"type": "version",
								"version": {
									"vulnerable": true,
									"fix_status": {
										"class": "fixed"
									},
									"package": {
										"name": "python-pillow-debuginfo",
										"architectures": [
											"aarch64",
											"x86_64"
										]
									},
									"affected": {
										"type": "rpm",
										"range": [
											{
												"lt": "0:5.1.1-12.el8_2"
											}
										],
										"fixed": [
											"0:5.1.1-12.el8_2"
										]
									}
								}
							},
							{
								"type": "version",
								"version": {
									"vulnerable": true,
									"fix_status": {
										"class": "fixed"
									},
									"package": {
										"name": "python-pillow-debugsource",
										"architectures": [
											"aarch64",
											"x86_64"
										]
									},
									"affected": {
										"type": "rpm",
										"range": [
											{
												"lt": "0:5.1.1-12.el8_2"
											}
										],
										"fixed": [
											"0:5.1.1-12.el8_2"
										]
									}
								}
							},
							{
								"type": "version",
								"version": {
									"vulnerable": true,
									"fix_status": {
										"class": "fixed"
									},
									"package": {
										"name": "python3-pillow",
										"architectures": [
											"aarch64",
											"x86_64"
										]
									},
									"affected": {
										"type": "rpm",
										"range": [
											{
												"lt": "0:5.1.1-12.el8_2"
											}
										],
										"fixed": [
											"0:5.1.1-12.el8_2"
										]
									}
								}
							},
							{
								"type": "version",
								"version": {
									"vulnerable": true,
									"fix_status": {
										"class": "fixed"
									},
									"package": {
										"name": "python3-pillow-debuginfo",
										"architectures": [
											"aarch64",
											"x86_64"
										]
									},
									"affected": {
										"type": "rpm",
										"range": [
											{
												"lt": "0:5.1.1-12.el8_2"
											}
										],
										"fixed": [
											"0:5.1.1-12.el8_2"
										]
									}
								}
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "rocky-errata",
		"raws": [
			"vuls-data-raw-rocky-errata/2020/RLSA-2020:3185.json"
		]
	}
}
